name: 'Field Group Settings'
type: module
description: Provides a field group display formatter for hiding settings.
package : Fields
# core: 8.x
dependencies:
  - field_group:field_group

# Information added by Drupal.org packaging script on 2018-06-13
version: '8.x-1.0'
core: '8.x'
project: 'field_group_settings'
datestamp: 1528892635
